esphome:
  name: tubeszb-mgm24
  name_add_mac_suffix: true

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server
  - source: ../components
    components: [uart]

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  platform: esphome

web_server:
  port: 80
  local: true

mdns:
  services:
    - service: "_zigbee"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1.0
        name: tubeszb-mgm24
        radio_type: ezsp

# Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

uart:
  id: uart_bus
  rx_pin: GPIO36
  tx_pin: GPIO4
  rts_pin: GPIO2
  cts_pin: GPIO13
  hw_flow_control: CTS_RTS
  baud_rate: 115200
  rx_buffer_size: 256

stream_server:
  uart_id: uart_bus
  port: 6638
  buffer_size: 256

binary_sensor:
  - platform: stream_server
    connected:
      name: "Serial Connected"

sensor:
  - platform: stream_server
    connection_count:
      name: "Connection Count"

switch:
  - platform: gpio
    pin: 5
    name: "RST Pin"
    id: rst_pin
    inverted: yes
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 16
    name: "Bootloader Pin"
    id: bootloader_pin
    inverted: yes
    restore_mode: ALWAYS_OFF
    disabled_by_default: true

button:
  - platform: restart
    name: "Restart"
    disabled_by_default: true

  - platform: template
    name: "Reset ZigBee Stack"
    id: reset_zigbee_stack
    disabled_by_default: true
    on_press:
      - switch.turn_on: rst_pin
      - delay: 15ms
      - switch.turn_off: rst_pin
